server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    gzip_static on;

    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ =404;
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=86400";
    }
}
