services:
  ws-server:
    build:
      context: .
      target: server
    environment:
      - WS_BIND_ADDR=0.0.0.0:9001
    ports:
      - "9001:9001"

  web:
    build:
      context: .
      target: web
    ports:
      - "8080:80"
    depends_on:
      - ws-server
